name: Update Homebrew Formula

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest GitHub release version
        id: release
        run: |
          VERSION=$(curl -s https://api.github.com/repos/adminneo-org/adminneo/releases/latest | jq -r '.tag_name' | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          ZIP_URL="https://www.adminneo.org/files/${VERSION}/__/adminneo-${VERSION}.zip"
          echo "ZIP_URL=$ZIP_URL" >> $GITHUB_ENV
          # Vérifie que le fichier .zip existe
          if ! curl --head --fail "$ZIP_URL"; then
            echo "Zip file does not exist, aborting."
            exit 1
          fi

      - name: Calculate SHA256 of zip
        run: |
          curl -L -o /tmp/adminneo.zip "$ZIP_URL"
          SHA256=$(sha256sum /tmp/adminneo.zip | awk '{print $1}')
          echo "SHA256=$SHA256" >> $GITHUB_ENV

      - name: Update Homebrew formula
        run: |
          FORMULA="Formula/adminneo.rb"
          sed -i "s|version \".*\"|version \"$VERSION\"|" $FORMULA
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" $FORMULA
          sed -i "s|url \".*\"|url \"$ZIP_URL\"|" $FORMULA

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "update-adminneo-${{ env.VERSION }}"
          title: "Update adminneo to ${{ env.VERSION }}"
          body: "Automatic update of adminneo formula to version ${{ env.VERSION }}."
          base: main
          labels: update
          token: ${{ secrets.PAT_TOKEN }}
